FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS publish
WORKDIR /src/
COPY . /src/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS runtime
ENV TZ=Africa/Johannesburg
WORKDIR /app
RUN apk add --no-cache tzdata \
        && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo "${TZ}" > /etc/timezone
COPY --from=publish /src/out ./
CMD ["dotnet", "dotnet-6-tz-bug.dll"]